%PRELAB3 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 15-Sep-2011 01:06:48
%

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N    = 16;       % Order
Fc   = 0.125;    % Cutoff Frequency

fir1(N, Fc)

% [EOF]
