function [B Hd h]= EllipticN8
%ELLIPTICN8 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 06-Oct-2011 12:39:41
%

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in kHz.
Fs = 8;  % Sampling Frequency

N     = 8;   % Order
Fpass = 1;   % Passband Frequency
Apass = 1;   % Passband Ripple (dB)
Astop = 80;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass('N,Fp,Ap,Ast', N, Fpass, Apass, Astop, Fs);
Hd = design(h, 'ellip');

B = dsp.BiquadFilter('SOSMatrix',Hd.sosMatrix,...
'ScaleValues',Hd.ScaleValues);

% [EOF]
