function Hd = problem10_2_a
%PROBLEM10_2_A Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 04-Dec-2011 23:35:22
%

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N    = 24;             % Order
Fc1  = 0.16666666667;  % First Cutoff Frequency
Fc2  = 0.33333333333;  % Second Cutoff Frequency
flag = 'scale';        % Sampling Flag

% Create the window vector for the design algorithm.
win = rectwin(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2], 'stop', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
